DATA_PATH:
  train_data: "data/processed/train_data.csv"
  val_data: "data/processed/val_data.csv"
  test_data: "data/processed/dev.csv"
  totto_target_summary: "data/processed/totto_cleaned_dev_data.jsonl"

GENERATED_PREDICTION:
  generated_txt: "artifacts/t5-small/generated_predictions.txt"

MODEL:
  OUTPUT_DIR: "artifacts/t5-small/"
  TEXT:
    MODEL_NAME: "facebook/bart-large-cnn"
  TABLE:
    MODEL_NAME: "t5-small"
  MODEL_PATH: "artifacts/t5-small/"