DATA_PATH:
  raw_data: "data/raw"
  processed_data: "data/processed"
  folder_name: "extracted_folders"
  train_data: "data/processed/train_data.csv"
  val_data: "data/processed/val_data.csv"
  test_data: "data/processed/dev.csv"

MODEL:
  PRETRAINED_MODEL: "facebook/bart-large-cnn"
  OUTPUT_DIR: "artifacts/t5-small/" # path to save model after training
  PREDICTIONS: # path to save model predictions
  INPUT_TYPE: "TABLE" # TEXT | TABLE
  FINETUNED_MODEL: "artifacts/t5-small/"
  
MODEL_PREDICTION:
  PATH: "test_output"